### ISSUE TITLE
Linux builds are not being uploaded

### ISSUE THREAD

**Issue by ajdawson** [conda-forge/gridfill-feedstock#9]
Something appears to be wrong in the Linux CircleCI builds, they work for PRs but fail when merged (e.g. https://circleci.com/gh/conda-forge/gridfill-feedstock/31). This means that none of the recent updates (PRs #6 and #7) actually created a new linux build on the conda-forge channel (https://anaconda.org/conda-forge/gridfill/files).

**Comment by ocefpaf** [comment]
I updated the token in #10 and now I'm restarting the CIs. The package should be in the channel in a few minutes.
